# Generated by Django 3.2.12 on 2022-03-21 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprecpro', '0002_comment_follow_like_post'),
        ('sprecpro', '0002_favorite'),
    ]

    operations = [
    ]
