# Generated by Django 3.2.12 on 2022-04-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprecpro', '0005_auto_20220327_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='song_uid',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
