# Generated by Django 3.2.12 on 2022-04-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprecpro', '0006_alter_favorite_song_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='featured_played_uid',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pronouns',
            field=models.TextField(null=True),
        ),
    ]
